Docker solving
LeichtensteinSpy/Education pull request #1
Opened 2023-07-10 13:51 UTC by LeichtensteinSpy

Made the new Dockerfile with new configuration including RUN and CMD param
All of this can show on port 3789 needed information

2023-07-11 06:06 UTC, MikkoArtik requested changes
Основные замечания:
- неоптимальное расположение команд;
- не используется Poetry-файл

2023-07-11 06:06 UTC, MikkoArtik commented on App/Dockerfile
> +RUN pip3 install uvicorn && pip3 install fastapi
Должно собираться без этого. Зачем тогда дан Poetry-файл?

2023-07-11 06:06 UTC, MikkoArtik commented on App/Dockerfile
> +RUN pip3 install uvicorn && pip3 install fastapi
неоптимальное расположение команд

2023-07-12 13:04 UTC, RoostiqueTheMan requested changes
Всё хорошо, есть пара моментов

2023-07-12 13:04 UTC, RoostiqueTheMan commented on App/Dockerfile
> +RUN apt-get -y update
лишняя строка, качается последняя версия пакета

2023-07-12 13:04 UTC, RoostiqueTheMan commented on App/Dockerfile
> +RUN poetry install --only main
#ASK 
можно ли обойтись без --only main

2023-07-12 13:25 UTC, MikkoArtik approved these changes
Можно сливать

2023-07-12 13:26 UTC, RoostiqueTheMan approved these changes
все хорошо

2023-07-12 13:27 UTC, merged