.dockerignore
LeichtensteinSpy/Education pull request #2
Opened 2023-07-13 10:23 UTC by LeichtensteinSpy

Made .dockerignore file for ignoring unneccessary files and folders. A tak ne ponyal, chto eshe ignorirovat mojno

2023-07-13 12:05 UTC, RoostiqueTheMan approved these changes

2023-07-13 12:14 UTC, RoostiqueTheMan requested changes
надо убрать звездочки

2023-07-13 13:18 UTC, RoostiqueTheMan approved these changes
Все хорошо

2023-07-13 13:27 UTC, RoostiqueTheMan approved these changes
все хорошо

2023-07-14 06:03 UTC, MikkoArtik approved these changes

2023-07-14 06:06 UTC, merged